apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
spec:
  secretName: api-cert
  dnsNames:
    - {{ .Values.domainApi }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
